### ISSUE TITLE
[FEATURE] Build a contributing guidelines file

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#235]
### Description of the feature request

A contributing guidelines file would make it much easier for other people to contribute to our project.
We can also add a guide to add new languages/translations.

### Additional information/context

What do you think about this? 🙂

**Comment by xgovernor** [comment]
I believe details like device specification, etc would be necessary in some cases.  You may consider this

**Comment by Panquesito7** [comment]
Not 100% sure that's required in our case. Probably more for the bug report template in most extreme cases, IMO.

**Comment by thomasthaddeus** [comment]
## Feature Request Template

```yaml
name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you start
        Check if your idea is already suggested by searching issues (open/closed).
        If it exists, please contribute to the existing one.

  - type: textarea
    id: feature-summary
    attributes:
      label: Summary
      description: Briefly describe the feature you want to be implemented.
    validations:
      required: true

  - type: textarea
    id: feature-motivation
    attributes:
      label: Motivation
      description: Why do you think this feature will be beneficial?
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the proposed feature.
    validations:
      required: true

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing issues
      description: Did you check if this request has been already reported?
      options:
        - label: I have checked existing issues (open and closed) for duplicates
          required: true

  - type: markdown
    attributes:
      value: |
        ## Screenshots / Mockups
        If applicable, add screenshots or mockups to help explain your feature request.
        Please upload these separately and provide the URLs in your response below.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshot / Mockup URLs
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or information that might be helpful.
    validations:
      required: false
```

This one is an upgrade to the feature request that could save you from creating a new form style.

**Comment by Panquesito7** [comment]
> This one is an upgrade to the feature request that could save you from creating a new form style.

Feel free to create a PR updating the current one. Thank you. 🙂

**Comment by thomasthaddeus** [comment]
Fantastic!

**Comment by Panquesito7** [comment]
Re-opening as that issue didn't solve the missing contributing guidelines file.

**Comment by thomasthaddeus** [comment]
https://github.com/TheAlgorithms/website/issues/235#issuecomment-1642522819

Have you tried a community health file?
just make a .github repo, and it serves all your repositories. It is useful when you point users to it and only have to update it in one place.

What about this? It can be added to another form or created separately and then the first three key values need changed...and the link

```yaml
name: Bug report
description: File a bug report
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## Before You Start...

        Please make sure you have read and understood our contributing guidelines:
        [**insert link to contributing guidelines here**](/)

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Acknowledgment
      description: Please check the box below before submitting your issue.
      options:
        - label: I have read and understood the contributing guidelines.

  - type: input
    id: title
    attributes:
      label: Title
      description: Briefly describe the issue.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a more detailed explanation of the issue.
    validations:
      required: true

  - type: input
    id: system-info
    attributes:
      label: System Info
      description: Please provide your system's OS, browser, etc.
    validations:
      required: false
```
